# Generated by Django 2.2.3 on 2019-09-05 06:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('current_value', models.DecimalField(decimal_places=6, default='0.00', max_digits=15, verbose_name='current value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'gauge',
                'verbose_name_plural': 'gauges',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('points', models.PositiveIntegerField(default=0)),
                ('unique', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'metric',
                'verbose_name_plural': 'metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(default=0, verbose_name='number')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='created')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_metrics.Metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'year metric',
                'verbose_name_plural': 'year metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(default=0, verbose_name='number')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='created')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_metrics.Metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'week metric',
                'verbose_name_plural': 'week metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('no_email', models.BooleanField(default=False, verbose_name='no e-mail')),
                ('send_daily', models.BooleanField(default=True, verbose_name='send daily')),
                ('send_weekly', models.BooleanField(default=False, verbose_name='send weekly')),
                ('send_monthly', models.BooleanField(default=False, verbose_name='send monthly')),
                ('email_recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='email recipients')),
                ('metrics', models.ManyToManyField(to='app_metrics.Metric', verbose_name='metrics')),
            ],
            options={
                'verbose_name': 'metric set',
                'verbose_name_plural': 'metric sets',
            },
        ),
        migrations.CreateModel(
            name='MetricMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(default=0, verbose_name='number')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='created')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_metrics.Metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'month metric',
                'verbose_name_plural': 'month metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='number')),
                ('item_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('item_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_metrics.Metric', verbose_name='metric')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metricitems', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'metric item',
                'verbose_name_plural': 'metric items',
            },
        ),
        migrations.CreateModel(
            name='MetricDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField(default=0, verbose_name='number')),
                ('created', models.DateField(default=datetime.date.today, verbose_name='created')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_metrics.Metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'day metric',
                'verbose_name_plural': 'day metrics',
            },
        ),
    ]
