# Generated by Django 2.2 on 2019-05-14 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 12, 24, 16, 787985, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 12, 24, 16, 788069, tzinfo=utc), verbose_name='updated'),
        ),
    ]
